@extends('layouts.app')

@section('header')
<div class="flex items-center justify-between">
    <h2 class="font-semibold text-3xl text-gray-800 leading-tight">
        Performance Report: {{ $report->staff->name }}
    </h2>

    <a href="{{ route('staff.reports.index') }}"
       class="px-4 py-2 bg-gray-600 text-white text-xl rounded hover:bg-gray-700">
        Back to Reports
    </a>
</div>
@endsection

@section('content')
<div class="w-full mx-auto bg-white shadow rounded-lg p-6 text-xl">

    <p><strong>Title:</strong> {{ $report->title }}</p>
    <p><strong>Total Hours:</strong> {{ $report->total_hours }}</p>
    <p><strong>Remarks:</strong> {{ $report->remarks ?? '—' }}</p>
    <p><strong>Period:</strong> {{ $report->period_start }} to {{ $report->period_end }}</p>
    <p><strong>Generated By System:</strong> {{ $report->generated_by_system ? 'Yes' : 'No' }}</p>
    <p><strong>Created At:</strong> {{ $report->created_at->format('d M Y H:i') }}</p>

</div>
@endsection
